# Generated by Django 3.1.2 on 2020-11-03 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateField()),
                ('content_title', models.CharField(max_length=200)),
                ('content_body', models.CharField(max_length=500)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.author')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('star', models.IntegerField()),
                ('feedback_content', models.CharField(max_length=200)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.blog')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.user')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='rating_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.rating'),
        ),
        migrations.AddField(
            model_name='author',
            name='blog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.blog'),
        ),
        migrations.AddField(
            model_name='author',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.user'),
        ),
    ]
