# Generated by Django 3.1.2 on 2020-11-04 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_auto_20201103_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='blog_id',
        ),
        migrations.AddField(
            model_name='author',
            name='blog_id',
            field=models.ManyToManyField(to='app_blog.Blog'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.user', unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='rating_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.rating', unique=True),
        ),
    ]
