# Generated by Django 3.1.2 on 2020-11-04 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_auto_20201104_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='rating_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_blog.rating'),
        ),
    ]
