# Generated by Django 3.1.2 on 2020-11-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_auto_20201104_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
    ]
