# Generated by Django 3.1.2 on 2020-11-04 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0007_auto_20201104_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='content_title',
            new_name='title',
        ),
    ]
