# Generated by Django 3.1.2 on 2020-11-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0008_auto_20201104_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author_id',
        ),
        migrations.AddField(
            model_name='blog',
            name='author_id',
            field=models.ManyToManyField(to='app_blog.Author'),
        ),
    ]
