# Generated by Django 3.1.2 on 2020-11-04 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0009_auto_20201104_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='blog_id',
        ),
        migrations.AddField(
            model_name='author',
            name='blog_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_blog.blog'),
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author_id',
        ),
        migrations.AddField(
            model_name='blog',
            name='author_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_blog.author'),
        ),
    ]
