# Generated by Django 3.1.2 on 2020-11-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0012_auto_20201104_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='rating_id',
            field=models.ManyToManyField(to='app_blog.Rating'),
        ),
    ]
