# Generated by Django 3.1.2 on 2020-11-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0014_auto_20201104_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='blog_id',
        ),
        migrations.AddField(
            model_name='author',
            name='blog_id',
            field=models.ManyToManyField(to='app_blog.Blog'),
        ),
    ]
