# Generated by Django 3.1.2 on 2020-11-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0020_auto_20201105_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
